<a href="https://colab.research.google.com/github/kjaid0341-creator/DATA-SCIENCE--1/blob/main/lec8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#JOINS

In [ ]:
# from os import rename
import pandas as pd
ddf=pd.read_csv("student_data.csv")
df1=pd.DataFrame({"id":[1,2,3,4],"name":["rewas","patil","moosa","andus"],"age":[25,30,35,40]})
df2=pd.DataFrame({"id":[3,4,5,6],"name":["moosa","andus","andusur","vadhusur"],"age":[25,30,35,40]})

df3=pd.merge(df1,df2, on="id", how='inner')#inner join
display(df3)
df3.rename(columns={'name_x':'name_df1','name_y':'name_df2'},inplace=True)#to rename the coloumn name
# inplace changes the orignal data frame bydefault False
display(df3)
df4=pd.merge(df1,df2, on="id", how='left')#left join
display(df4)
df5=pd.merge(df1,df2, on="id", how='right')#right join
display(df5)
df6=pd.merge(df1,df2, on="id", how='outer')#outer join
display(df6)

# cross join
df7=pd.merge(df1,df2, how='cross')#left join
display(df7)

   id name_x  age_x name_y  age_y
0   3  moosa     35  moosa     25
1   4  andus     40  andus     30

   id name_df1  age_x name_df2  age_y
0   3    moosa     35    moosa     25
1   4    andus     40    andus     30

   id name_x  age_x name_y  age_y
0   1  rewas     25    NaN    NaN
1   2  patil     30    NaN    NaN
2   3  moosa     35  moosa   25.0
3   4  andus     40  andus   30.0

   id name_x  age_x    name_y  age_y
0   3  moosa   35.0     moosa     25
1   4  andus   40.0     andus     30
2   5    NaN    NaN   andusur     35
3   6    NaN    NaN  vadhusur     40

   id name_x  age_x    name_y  age_y
0   1  rewas   25.0       NaN    NaN
1   2  patil   30.0       NaN    NaN
2   3  moosa   35.0     moosa   25.0
3   4  andus   40.0     andus   30.0
4   5    NaN    NaN   andusur   35.0
5   6    NaN    NaN  vadhusur   40.0

    id_x name_x  age_x  id_y    name_y  age_y
0      1  rewas     25     3     moosa     25
1      1  rewas     25     4     andus     30
2      1  rewas     25     5   andusur     35
3      1  rewas     25     6  vadhusur     40
4      2  patil     30     3     moosa     25
5      2  patil     30     4     andus     30
6      2  patil     30     5   andusur     35
7      2  patil     30     6  vadhusur     40
8      3  moosa     35     3     moosa     25
9      3  moosa     35     4     andus     30
10     3  moosa     35     5   andusur     35
11     3  moosa     35     6  vadhusur     40
12     4  andus     40     3     moosa     25
13     4  andus     40     4     andus     30
14     4  andus     40     5   andusur     35
15     4  andus     40     6  vadhusur     40

In [ ]:
# concatination
df1=pd.DataFrame({"id":[3,4,5,6],"name":["moosa","andus","andusur","vadhusur"],"age":[25,30,35,40]})
df2=pd.DataFrame({"id":[1,2,3,4],"name":["rewas","patil","moosa","andus"],"age":[25,30,35,40]})
# pd.concat([df1,df2])
display(pd.concat([df1,df2]))
df3=pd.merge(df1,df2, on="id", how='inner')#inner join
display(df3)

   id      name  age
0   3     moosa   25
1   4     andus   30
2   5   andusur   35
3   6  vadhusur   40
0   1     rewas   25
1   2     patil   30
2   3     moosa   35
3   4     andus   40

   id name_x  age_x name_y  age_y
0   3  moosa     25  moosa     35
1   4  andus     30  andus     40

In [ ]:
# drop dublicates
df=pd.DataFrame({"id":[3,4,5,6,6,3,3],"name":["moosa","andus","andusur","vadhusur","kalusur","niggasur","nanasur"],"age":[25,30,35,40,50,30,90]})
df1=df.drop_duplicates(subset=["id"],keep="first")
# display(df1
# keep-> if you want to keep last value or first
display(df1)

   id      name  age
0   3     moosa   25
1   4     andus   30
2   5   andusur   35
3   6  vadhusur   40

In [ ]:
# to convert string format date to a normal date in pandas
# pd.to_datetime()
df=ddf.pivot_table(columns='placement_status',index='sleep_hours',values="exam_score",aggfunc='mean')
display(df)

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [ ]:
# col study hts,rows sleep shrs,values ass compl
df=ddf.pivot_table(columns='study_hours',index='sleep_hours',values="assignments_completed",aggfunc='mean')
display(df)

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844

In [ ]:
# hw 1327,511,586,1050,185,1179,182